import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";
import deved from "../images/pics/hacker.png";
import next from "next";
import Projects from "./components/Projects.js";
import Halloffame from "./components/halloffame.js";
import Services from "./components/Services.js";
import Logo from "../images/icons/newlogo.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <>
    <section className=" lg:snap-y lg:snap-mandatory lg:h-screen lg:overflow-scroll lg:scroll-smooth lg:no-scrollbar lg:overflow-y-scroll">
      <div className={darkMode ? "dark" : ""}>
        <main className=" bg-white px-10 md:px-20 dark:bg-gray-900 ">

          <section className=" lg:h-screen lg:snap-start lg:flex lg:items-center lg:justify-center">
            <Head>
                <title>VZsecure - The Eagle-Eye Protection</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" type="image/x-icon" href="./title.png" />
            </Head>
            <section className="min-h-screen">
                <div>
                <nav className=" py-3 mb-10 flex justify-between md:text-sm">
                  <div className=" pt-5">
                    <Image src={Logo} alt="logo" height={75} width={250} className=" rounded-lg"/>
                  </div>
                  <ul className="flex items-center gap-10 right-10">
                    <li>
                      <BsFillMoonStarsFill
                      onClick={() => setDarkMode(!darkMode)}
                      className=" cursor-pointer text-2xl text-black dark:text-white "
                    />
                    </li>
                    <a href="https://medium.com/@vaibhavmadan2002" target="_blank" rel="noreferrer">
                      <li className=" text-xl font-burtons bg-gradient-to-b from-lime-500 to-teal-500 text-white px-4 py-2 rounded-md shadow-lg shadow-cyan-400">
                        Blog
                      </li>
                    </a>
                  </ul>
                </nav>
                </div>
                <div className=" text-center p-4">
                <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl drop-shadow-lg font-serif">
                    Vaibhav Zadane
                </h2>
                <h3 className=" text-2xl py-2 md:text-3xl dark:text-white font-serif">
                    CyberSecurity Expert and Malware Analyzer
                </h3>
                <hr className=" w-80 h-1 mx-auto border-2 rounded md:my-10 drop-shadow-xl" />
                <p className=" text-lg py-5 leading-8 text-gray-800 md:text-xl mal-w-xl mx-auto lg:mr-60 lg:ml-60 dark:text-white">
                Hello People, Welcome to you all. I am a <span className=" text-teal-600 text-2xl">Cyber-Security, Malware Analyzer</span> and <span className=" text-teal-600 text-2xl"> Developer</span> from India. For the last 1 year+ I have been working in these domains 
                and I have the relevant experience and skill that is required. I have experience at 
                an Industry level in Cyber-Security as I have completed an Internship. I do Freelancing 
                in Bug Bounty and Spreading knowledge related to security.
                </p>
                </div>
                
                <div className=" shadow-lg shadow-cyan-400 relative bg-gradient-to-b overflow-hidden from-white rounded-full w-80 h-80 mx-auto md:h-96 md:w-96 dark:from-lime-500 dark:to-teal-500">
                <Image src={deved} layout="fill" objectFit="cover" alt="deved" />
                </div>
            </section>
          </section>

          <Services />

          <Projects />

          <Halloffame />

          
        </main>
      </div>
    </section>
    </>
  );
}
