import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import Twitter from "../images/icons/twitter.svg";
import Facebook from "../images/icons/facebook.svg";
import Instagram from "../images/icons/instagram.svg";
import Linkedin from "../images/icons/linkedin.svg"
import Image from "next/image";
import deved from '../images/pics/hacker.png';
import design from '../images/pics/design.png'
import code from '../images/pics/code.png'
import Consulting from '../images/pics/consulting.png'
import { useState } from "react";
import SSRpage from "./ssr-page";


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Portfolio of VZsecure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className=" py-5 mb-10 flex justify-between">
            <h1 className=" text-xl font-burtons bg-gradient-to-r  from-lime-500 to-teal-500 text-white px-4 py-2 rounded-md shadow-lg shadow-cyan-400">Developed by Vzsecure</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode) } className=" cursor-pointer text-2xl text-black dark:text-white" />
              </li>
              <li>
                <a className=" bg-gradient-to-r  from-lime-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 shadow-lg shadow-cyan-400" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl drop-shadow-lg">Vaibhav Zadane</h2>
            <h3 className=" text-2xl py-2 md:text-3xl dark:text-white" >CyberSecurity Exert and Malware Analyzer</h3>
            <hr className=" w-80 h-1 mx-auto border-2 rounded md:my-10 drop-shadow-xl" />
            <p className=" text-lg py-5 leading-8 text-gray-800 md:text-xl mal-w-xl mx-auto lg:mr-60 lg:ml-60 dark:text-white">
              Hello, Welcome you all to my profile. <br /> 
              I am Cyber Security Expert. Since from last 1 year I am in these field working as a freelancer 
              and completed by internship. I have experience in the filed like Ethical Hacking, Penetration Testing, 
              Network Security, Malware Alalyst, Programmer. Righ now I am pursuing my BSC-IT degree and completing serveral 
              courses related to this field. 
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 " >
            <a href="#"><Image src={Twitter} alt="Twitter" /></a>
            <a href="#"><Image src={Linkedin} alt="Linkedin"/></a>
            <a href="#"><Image src={Facebook} alt="Facebook" /></a>
            <a href="#"><Image src={Instagram} alt="Instagram" /></a>
          </div>
          <div className=" shadow-lg shadow-cyan-400 relative bg-gradient-to-b overflow-hidden from-white rounded-full w-80 h-80 mt-20 mx-auto md:h-96 md:w-96 dark:from-lime-500 dark:to-teal-500">
            <Image src={deved} layout="fill" objectFit="cover" alt="deved"/>
          </div>
        </section>
        <hr className=" w-80 h-1 mx-auto border-2 rounded md:my-10 dark:bg-lime-500" />
        <section className=" text-center mt-10">
          <div>
            <h2 className=" text-3xl py-1 dark:text-white">Services I Offer</h2>
            <p className=" text-lg py-5 leading-8 text-gray-800 md:text-xl mal-w-xl mx-auto lg:mr-60 lg:ml-60 dark:text-white">
              Since in the begining of my journey I have done with the internship and bougbounty as well <br/>
              I offer from a wide range of services including programming and teachine
            </p>
          </div>
          <div className=" lg:flex gap-10 mt-10">
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white lg:ml-28 md:flex-row">
              <Image src={ design } width={100} height={100} alt="design" />
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Create elegent design suited for you need design theory</p>
              <h4 className="py-4 text-teal-600">Tools I use</h4>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={ code } width={100} height={100} alt="code" />
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Create elegent design suited for you need design theory</p>
              <h4 className="py-4 text-teal-600">Tools I use</h4>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={ Consulting } width={100} height={100} alt="consultins" />
              <h3 className=" text-lg font-medium pt-8 pb-2">Beautiful Design</h3>
              <p className="py-2">Create elegent design suited for you need design theory</p>
              <h4 className="py-4 text-teal-600">Tools I use</h4>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Photoshop</p>
            </div>
          </div>
        </section>
        <section className=" text-center">
          <div>
            <h3 className=" text-3xl py-1">
              Projects
            </h3>
            <p className=" text-md py-2 leading-8 text-gray-800">
              Since in the begining of my journey I have done with the internship and bougbounty as well
            </p>
            <p>
              I offer from a wide range of services including programming and teachine
            </p>
          </div>
          <div>
            <div>
              <Image src={code} alt="test" />
            </div>
          </div>
        </section>
      </main>
      <SSRpage />
    </div>
  );
}


